#!/usr/bin/env python3
"""Fast, engine-independent validation for the Namma City repository."""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
EXPECTED = (
    "NammaCity.uproject",
    "Config/DefaultEngine.ini",
    "Config/DefaultGame.ini",
    "Source/NammaCity.Target.cs",
    "Source/NammaCityEditor.Target.cs",
    "Source/NammaCity/NammaCity.Build.cs",
    "Source/NammaCity/NammaCity.cpp",
    "Source/NammaCity/NammaCity.h",
    ".gitattributes",
    ".gitignore",
)
LFS_EXTENSIONS = {
    ".uasset",
    ".umap",
    ".fbx",
    ".blend",
    ".wav",
    ".flac",
    ".mp3",
    ".mp4",
    ".mov",
    ".mkv",
    ".exr",
    ".hdr",
    ".png",
    ".tga",
    ".psd",
}
ASSET_PREFIXES = {
    ".umap": ("L_",),
    ".uasset": (
        "A_",
        "BP_",
        "DA_",
        "DT_",
        "M_",
        "MI_",
        "NS_",
        "S_",
        "SK_",
        "SM_",
        "T_",
        "WBP_",
    ),
}


def check_command(command: list[str]) -> bool:
    return subprocess.run(command, cwd=ROOT, capture_output=True, check=False).returncode == 0


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    for relative in EXPECTED:
        if not (ROOT / relative).is_file():
            errors.append(f"missing required file: {relative}")

    try:
        project = json.loads((ROOT / "NammaCity.uproject").read_text(encoding="utf-8"))
        modules = {item.get("Name") for item in project.get("Modules", [])}
        if "NammaCity" not in modules:
            errors.append("NammaCity.uproject does not declare the NammaCity module")
    except (OSError, json.JSONDecodeError) as exc:
        errors.append(f"invalid NammaCity.uproject: {exc}")

    attributes = (ROOT / ".gitattributes").read_text(encoding="utf-8")
    for extension in sorted(LFS_EXTENSIONS):
        if not re.search(rf"^\*\{extension}\s+filter=lfs\b", attributes, re.MULTILINE):
            errors.append(f"missing Git LFS rule for *{extension}")

    content = ROOT / "Content"
    for path in content.rglob("*"):
        if not path.is_file() or path.name == ".gitkeep":
            continue
        prefixes = ASSET_PREFIXES.get(path.suffix.lower())
        if prefixes and not path.stem.startswith(prefixes):
            errors.append(f"asset name lacks an approved prefix: {path.relative_to(ROOT)}")

    if not check_command(["git", "rev-parse", "--is-inside-work-tree"]):
        warnings.append("Git repository has not been initialized")
    elif not check_command(["git", "lfs", "env"]):
        errors.append("Git LFS is not available in this repository")

    if not (content / "NammaCity/Maps/L_SmokeTest.umap").is_file():
        warnings.append("smoke-test map has not been generated by Unreal Editor")

    for warning in warnings:
        print(f"WARNING: {warning}")
    for error in errors:
        print(f"ERROR: {error}")

    if errors:
        print(f"Repository validation failed with {len(errors)} error(s).")
        return 1
    print(f"Repository validation passed with {len(warnings)} warning(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
